name: microservice

services:
  text-split:
    container_name: microservice-text-split
    build: 
      dockerfile: ./build/Dockerfile
      context: .
    restart: always
    ports:
      - '8000:8000'