name: Style

on: push

jobs:
  wemake-python-styleguide:
    runs-on: ubuntu-22.04

    steps:
    - name: Copy code
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: python -m pip install -r requirements.txt
    
    - name: Check code style
      run: |
        python -m pip install wemake-python-styleguide==0.19.2
        python -m flake8 .



